version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=MultiChat
    volumes:
      - type: volume
        target: /var/lib/mongoDB
      - type: bind
        source: ./mongod.conf
        target: /etc/mongod.conf
      - type: bind
        source: ./MultichatKey
        target: /etc/MultichatKey
    command: mongod -f /etc/mongod.conf --auth --bind_ip_all 
